Repository Burgyn/MMLib.SwaggerForOcelot, pull requests merged in 2020-06, with the labels that each got.

#103 Fix empty route in ServiceDiscovery
  src/MMLib.SwaggerForOcelot/ServiceDiscovery/SwaggerServiceDiscoveryProvider.cs
  tests/MMLib.SwaggerForOcelot.Tests/ServiceDiscovery/SwaggerServiceDiscoveryProviderShould.cs
Labels: bug

#105 Allow programmatic configuration of SwaggerEndpoints
  README.md
  demo/ApiGateway/Startup.cs
  demo/ApiGatewayWithPath/Startup.cs
  src/MMLib.SwaggerForOcelot/Middleware/BuilderExtensions.cs
  tests/MMLib.SwaggerForOcelot.Tests/BuilderExtensionsShould.cs
Labels: feature, refactor 🛠️

#109 Added feature with multiflile configuration in ocelot and swagger
  .gitignore
  README.md
  demo/ApiGateway/ApiGateway.csproj
  demo/ApiGateway/Configuration/ocelot.SwaggerEndPoints.json
  demo/ApiGateway/Configuration/ocelot.contacts.json
  demo/ApiGateway/Configuration/ocelot.global.json
  demo/ApiGateway/Configuration/ocelot.orders.json
  demo/ApiGateway/Configuration/ocelot.projects.json
  demo/ApiGateway/Program.cs
  demo/ApiGateway/Startup.cs
  demo/ApiGateway/ocelot.json
  demo/OrderService/web.config
  src/MMLib.SwaggerForOcelot/Configuration/RouteOptions.cs
  src/MMLib.SwaggerForOcelot/Configuration/SwaggerEndPointOptions.cs
  src/MMLib.SwaggerForOcelot/Configuration/SwaggerFileConfiguration.cs
  src/MMLib.SwaggerForOcelot/Configuration/SwaggerFileRoute.cs
  src/MMLib.SwaggerForOcelot/Configuration/SwaggerForOcelotFileOptions.cs
  src/MMLib.SwaggerForOcelot/DependencyInjection/ConfigurationBuilderExtensions.cs
  src/MMLib.SwaggerForOcelot/DependencyInjection/ServiceCollectionExtensions.cs
  src/MMLib.SwaggerForOcelot/Middleware/SwaggerForOcelotMiddleware.cs
  src/MMLib.SwaggerForOcelot/ReRouteOptionsExtensions.cs
  src/MMLib.SwaggerForOcelot/RouteOptionsExtensions.cs
  src/MMLib.SwaggerForOcelot/ServiceDiscovery/ISwaggerServiceDiscoveryProvider.cs
  src/MMLib.SwaggerForOcelot/ServiceDiscovery/SwaggerServiceDiscoveryProvider.cs
  src/MMLib.SwaggerForOcelot/Transformation/ISwaggerJsonTransformer.cs
  src/MMLib.SwaggerForOcelot/Transformation/SwaggerJsonTransformer.cs
  tests/MMLib.SwaggerForOcelot.Tests/DummySwaggerServiceDiscoveryProvider.cs
  tests/MMLib.SwaggerForOcelot.Tests/RouteOptionsExtensionsShould.cs
  tests/MMLib.SwaggerForOcelot.Tests/ServiceDiscovery/SwaggerServiceDiscoveryProviderShould.cs
  tests/MMLib.SwaggerForOcelot.Tests/SwaggerForOcelotMiddlewareShould.cs
  tests/MMLib.SwaggerForOcelot.Tests/SwaggerForOcelotShould.cs
  tests/MMLib.SwaggerForOcelot.Tests/TestCase.cs
  tests/MMLib.SwaggerForOcelot.Tests/Tests/BasicConfiguration.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/BasicConfigurationWithVirtualDirectory.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/ConfigurationContainsOnlyPostMethods.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/ConfigurationIsSplitByControllers.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/ConfigurationIsSplitToSomeParts.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/Issue_65.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/NestedClasses.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/OcelotRouteOnlyOneController.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/OpenApiWithBasicConfiguration.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/OpenApiWithHostOverridden.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/OpenApiWithHostOverriddenWhenUpstreamAndDownstreamPathsAreDifferent.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/OpenApiWithServers.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/OpenApiWithVirtualDirectory.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/SwaggerContainsInnerReferenceDefinition.json
  tests/MMLib.SwaggerForOcelot.Tests/Tests/SwaggerWithBasePath.json
Labels: feature
